### ISSUE TITLE
프로젝트 세팅

### ISSUE THREAD

**Issue by chaneeii** [Nexters/www-iOS#2]
## Story
WWW 프로젝트를 세팅한다

## Task
- [ ] Tuist 
- [ ] 폴더구조 및 아키텍처 설계 (MVVM-C)
- [ ] 패키지 설치 (SnapKit, Rx-)
- [ ] 기본 코드 템플릿 등록
