### ISSUE TITLE
메인 홈 UI 추가작업(예정)

### ISSUE THREAD

**Issue by kokojong** [Nexters/www-iOS#47]
## Task

조금씩 비어있는 부분을 채울 예정입니다(일단 다른거 먼저,,,!)
까묵기 전에 써두기

## todo
- [x] 투표 상태에 따른 UI 변경
- [x] page label UI, 페이지에 맞게 변경, empty 할 때 처리
- [x] 설정 Button 추가 및 연결
- [x] emptyLabel
- [x] 캐릭터 이미지 크기 조절
- [x] union 이미지 변경
