### ISSUE TITLE
캘린더 UI 및 동작 일치

### ISSUE THREAD

**Issue by kokojong** [Nexters/www-iOS#58]
## Task

AOS와 동작을 일치 시키고 UI 미적용 된 사항을 적용한다.

## todo
- [ ] 캘린더 날짜 선택 AOS와 동작 일치
- [ ] UI에서 빠져있는 요소 적용(선택된 UI)
- [ ] 선택 불가한 경우에 대한 처리
- [ ] 선택 불가한 경우 Toast메세지 출력
