### ISSUE TITLE
네트워크 기본세팅

### ISSUE THREAD

**Issue by kokojong** [Nexters/www-iOS#8]
## Task
Moya 네트워크 기본세팅

## todo
- [x] user/join API를 예시로 네트워크 부분 테스트
- [x] repository, DAO 추가
- [x] VM 수정
- [x] DTO -> Domain 수정
