### ISSUE TITLE
MainRoom 수정사항

### ISSUE THREAD

**Issue by kokojong** [Nexters/www-iOS#90]
## Task

MainRoom에 빠진 부분을 채워 넣는다

## todo
- [ ] navController UI 및 화면과 연결
- [x] LargeButton 구현 및 상태 관리
- [ ] LargeButton 상태에 따른 동작 구현
- [ ] LinkButton 동작 구현
- [ ] 약속방 참여자(전체 인원) UI 연결
